# 从hub拉取镜像，用于服务器部署
# docker compose -f ./compose.CD.yaml up --build

# 依赖的外部文件：
# 1. 项目中的后端环境变量文件
# 2. 项目中的nginx文件夹
# 3. docker-data文件夹
services:

  prisma-ai-backend:
    image: onlyie/prisma-ai-hub-backend:2.9.0
    depends_on:
      mysql-container:
        condition: service_healthy
      redis-container:
        condition: service_healthy
    restart: unless-stopped
    container_name: prisma-ai-hub-backend
    env_file:
      - ./packages/backend/.env
      - ./packages/backend/.env.production
    environment:
      NODE_ENV: production
      # 生产环境下的prisma数据库连接配置
      DATABASE_URL: mysql://root:Qwqw1314!@mysql-container:3306/prisma-hub-v2?connection_limit=30&connect_timeout=10&pool_timeout=20&socket_timeout=60
      TASK_MAX_CONCURRENT: 30
    ports:
      - '3003:3003'
    volumes:
      - ./docker-data/nest-app/logs:/app/packages/backend/logs

  nginx-container:
    image: onlyie/prisma-ai-hub-nginx:1.0.0
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./packages/frontend/dist:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx # Nginx 日志
      - ./nginx/conf/default.remote.conf:/etc/nginx/conf.d/default.conf # Nginx 配置
      - /etc/nginx/ssl:/etc/nginx/ssl
    restart: unless-stopped
    depends_on:
      - prisma-ai-backend
      # - minio-container
  mysql-container:
    image: mysql
    #占用的主机端口:网络内访问使用的端口
    ports:
      - '3309:3306'
      # 目录内不能有文件,否则报错
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    environment:
      # 初始数据库
      MYSQL_DATABASE: prisma-ai
      MYSQL_ROOT_PASSWORD: prisma-ai
      # 允许任何主机连接
      MYSQL_ROOT_HOST: '%'
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-container:
    image: redis
    ports:
      - '6377:6379'
    volumes:
      - ./docker-data/redis:/data
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
  #使用默认桥接网络
